[I 2024-12-28 09:05:01,806] A new study created in RDB with name: TabNet_Boston
[W 2024-12-28 09:05:02,200] Trial 0 failed with parameters: {'n_d': 48, 'n_steps': 5, 'gamma': 1.792811241282387, 'cat_emb_dim': 3, 'n_independent': 2, 'n_shared': 1, 'momentum': 0.042077735969412354, 'mask_type': 'entmax'} because of the following error: ValueError('If cat_dims is non-empty, cat_idxs must be defined as a list of same length.').
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
[W 2024-12-28 09:05:02,202] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main(arguments)
  File "train.py", line 157, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
srun: error: stud-000: task 0: Exited with exit code 1
[I 2024-12-28 09:05:11,533] A new study created in RDB with name: TabNet_Socmob
[W 2024-12-28 09:05:11,830] Trial 0 failed with parameters: {'n_d': 48, 'n_steps': 8, 'gamma': 1.282418778054071, 'cat_emb_dim': 3, 'n_independent': 4, 'n_shared': 5, 'momentum': 0.007469603069357302, 'mask_type': 'sparsemax'} because of the following error: ValueError('If cat_dims is non-empty, cat_idxs must be defined as a list of same length.').
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
[W 2024-12-28 09:05:11,831] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main(arguments)
  File "train.py", line 157, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
srun: error: stud-000: task 0: Exited with exit code 1
[I 2024-12-28 09:05:26,293] A new study created in RDB with name: TabNet_Sensory
[W 2024-12-28 09:05:26,559] Trial 0 failed with parameters: {'n_d': 15, 'n_steps': 7, 'gamma': 1.8892475627905139, 'cat_emb_dim': 3, 'n_independent': 2, 'n_shared': 4, 'momentum': 0.06328702437693877, 'mask_type': 'entmax'} because of the following error: ValueError('If cat_dims is non-empty, cat_idxs must be defined as a list of same length.').
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
[W 2024-12-28 09:05:26,560] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main(arguments)
  File "train.py", line 157, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
srun: error: stud-000: task 0: Exited with exit code 1
[I 2024-12-28 09:05:41,282] A new study created in RDB with name: TabNet_Moneyball
[W 2024-12-28 09:05:41,563] Trial 0 failed with parameters: {'n_d': 23, 'n_steps': 8, 'gamma': 1.2465135675375256, 'cat_emb_dim': 3, 'n_independent': 1, 'n_shared': 4, 'momentum': 0.0018676494085009601, 'mask_type': 'entmax'} because of the following error: ValueError('If cat_dims is non-empty, cat_idxs must be defined as a list of same length.').
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
[W 2024-12-28 09:05:41,564] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main(arguments)
  File "train.py", line 157, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 530, in check_embedding_parameters
    raise ValueError(msg)
ValueError: If cat_dims is non-empty, cat_idxs must be defined as a list of same length.
srun: error: stud-000: task 0: Exited with exit code 1
[I 2024-12-28 09:05:50,999] A new study created in RDB with name: TabNet_Black_Friday
[W 2024-12-28 09:05:51,257] Trial 0 failed with parameters: {'n_d': 24, 'n_steps': 5, 'gamma': 1.0817568922930016, 'cat_emb_dim': 3, 'n_independent': 4, 'n_shared': 2, 'momentum': 0.021543231699696096, 'mask_type': 'entmax'} because of the following error: ValueError('The lists cat_dims and cat_idxs must have the same length.').
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 533, in check_embedding_parameters
    raise ValueError(msg)
ValueError: The lists cat_dims and cat_idxs must have the same length.
[W 2024-12-28 09:05:51,257] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main(arguments)
  File "train.py", line 157, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 133, in __call__
    model = self.model_name(trial_params, self.args)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tabnet.py", line 28, in __init__
    self.model = TabNetRegressor(**self.params)
  File "<string>", line 29, in __init__
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py", line 119, in __post_init__
    super(TabNetRegressor, self).__post_init__()
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 88, in __post_init__
    updated_params = check_embedding_parameters(self.cat_dims,
  File "/home/mburu/.local/lib/python3.8/site-packages/pytorch_tabnet/utils.py", line 533, in check_embedding_parameters
    raise ValueError(msg)
ValueError: The lists cat_dims and cat_idxs must have the same length.
srun: error: stud-000: task 0: Exited with exit code 1
